import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import estudos from "@/utils/estudos";
import { useState } from "react";

export default function Home() {
  const [value, setValue] = useState('');

  const mudarTexto = (e: React.ChangeEvent<HTMLInputElement>) => {
    setValue(e.target.value)
  }

  return (
    <>
      <Head>
        <title>Estudo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.header}>
        <div>
          <input
            type="text"
            className={styles.search}
            placeholder="Pesquisar..."
            onChange={(e) => mudarTexto(e)}
          />
        </div>
      </div>

      <div className={styles.content}>
        <div className={styles.middle}>
          {estudos.map((item, index) => (
            <>
              {item.tags.toLowerCase().includes(value.toLowerCase()) ?
                <div className={styles.mapEach} key={index}>
                  <div className={styles.title}>{item.titulo}</div>
                  <div className={styles.imgArea}>
                    <img src={item.img} alt="" className={styles.img} />
                    {item.img2 != '' ?
                      <img src={item.img2} alt="" className={styles.im2} />
                      :
                      ''
                    }
                  </div>
                  {item.link != '' ?
                    <a href={item.link} target="_blank" className={styles.codigo}><div>Código</div>  </a>
                    :
                    ''
                  }
                </div>
                :
                ''
              }
            </>
          ))}
        </div>
      </div>
    </>
  );
}
